# Generated by Django 5.1 on 2024-08-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('founding', '0005_alter_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firse_name',
            new_name='first_name',
        ),
    ]
