# Generated by Django 5.1 on 2024-08-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founding', '0007_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
