# Generated by Django 5.1 on 2024-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founding', '0008_projectpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
