# Generated by Django 5.1 on 2024-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founding', '0010_alter_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
    ]
